---
sudo: false
dist: trusty
language: node_js
node_js:
  - '8.3'
  - '8'
  - '10'

cache:
  directories:
    - node_modules

before_install:
  - npm i -g npm@6
  - touch package.json

install:
  - make install
  - make precompile

script:
  - make lint
  - make test

after_success:
  - make coverage
  - cat coverage/lcov.info | node_modules/.bin/coveralls

env:
  global:
    # GH_TOKEN
    - secure: KAfoKO+HsU18FwyAfOlKrqC0rfPdPQwaeibr0YnUqW2EmvFOGiuD6go4iFjLKEIc4V19k1JVdJX8p8Lqo5sDH/CqSDFoaKkxqFWfvgsfSiNrfMpVyFBSOPpSWtAfB7Y2+v4EHEtDiTMBjuWTz7ueSU+vtgei0abgeqwax2BFOTNvzczfe/yC5EfHCKIgwuojV0Ya1aNo5E5ZCx23/sqhWEjBBE+3nFUxsCgxuAgG3YlkFxDXIHzsmz+WDdYWcf5RJJTGfW35Tzqu8g0XA0VaiFLtySoXT+q7LpWyI6okU3T88JV8PDldZEZORICj7YrHzDwPb5yG8sCO7IJWZ8UlLhUww2BUIEFWpaB3q/FqIZuVeeIfwZ+JKko31FXQ9e9VtbxPwePeYc1wu8tYM5KUvLKEJ/UQNPJY63T+D2Tu84wNKTMAn/1JbIXlMolFhVvpNIU8AKMebt+R2UfPddu5hAbKdcB/lTSGKffRtO+WxwikPIrbKR0xBM25cWFt6yhLTHcVspomT9ZgR5tt/T1IW7fVGi/Vjqv8vmJc7pqakn1Pca1RuWXlDLt3ppyPdaI1+e3PKHL72h2wheJBEMs5vkFjFOphcspVbQ8+y41X0OIHyt2DCp6U5wImraKdtBd14o4rOkzfLmSC9bKY3oWZIIVI8AbU4H3RWzC84KGdgeY=
    # NPM_TOKEN
    - secure: EWccBaWwl3Kw3PVQfMuGezIqZ1czpVDRHgjcKtnwJx6lGAUGEsP38GisZP8B/nPE89ApO6jy8DL0KkQA4pk1Nd9KcV1vhj37aaWxZmi8EVfgif28xTuz1FPjnPTshiMbLHdzNTzrL89XApycaHRY31OJHlHox3c0PTSNMEnyygyGfC7gZyMYiwzOpR3f8+iPbx5s8MXOnmFlTGyr7NQ1NZW6CgyHpQMZ0ef1U88Ygc/QeRkNaUS9/duSYmks7zYufsGxwTjqKtIhh+S03+ywcDFs8HW42C8pBR5YEw8jzQrzGaDPfq42RtHHecdGManLIDgttOtaXp0XxArrRIkr2BMmojbW1BU/iDDSlJYwzW7R8cIesYGGUbdwnBi3vTKBf9aVTnd1zJI6H2mlwNuE4q1ZEnLNmeuEY8HRdZs98yGCAeHST4/nrDQOlb4UeRihX8UMqkYvbi/JOk03rY5VJEtMLJ6gzOVQciPrIT+cA9wVnTzDwr7je1q6X591IeZcncjtM0Qy+jq42UgS/PnPJ3ws044Gs/2H2sg24ZaEcfBO7HhCObcEqLFcSKoxgEpfynXyTvzIJ7Q/StnVS7rNn138Nu4guJTNZndv4E90osxjFzdYM/1HMUuc1kpGMcxlUjJU7iJ0/2uYGCqnb4LPTDc92JnCCclsIHrLsVpVoQQ=

deploy:
  skip_cleanup: true
  provider: script
  script: utils/release.sh
  on:
    repo: strvcom/atlas.js
    all_branches: true
    condition: $TRAVIS_BRANCH =~ ^release\/.{1,}$
    node_js: '10'
