---
sudo: false
dist: trusty
language: node_js
node_js:
  - '8.3'
  - '8'
  - '10'
matrix:
  allow_failures:
    - node_js: '10'

cache:
  directories:
    - node_modules

before_install:
  - npm i -g npm@6
  - touch package.json

install:
  - make install

script:
  - make lint
  - make test

after_success:
  - make coverage
  - cat coverage/lcov.info | node_modules/.bin/coveralls

env:
  global:
    # This configures the release script to which tag the release should be published
    - NPM_DISTTAG=latest
    - secure: KAfoKO+HsU18FwyAfOlKrqC0rfPdPQwaeibr0YnUqW2EmvFOGiuD6go4iFjLKEIc4V19k1JVdJX8p8Lqo5sDH/CqSDFoaKkxqFWfvgsfSiNrfMpVyFBSOPpSWtAfB7Y2+v4EHEtDiTMBjuWTz7ueSU+vtgei0abgeqwax2BFOTNvzczfe/yC5EfHCKIgwuojV0Ya1aNo5E5ZCx23/sqhWEjBBE+3nFUxsCgxuAgG3YlkFxDXIHzsmz+WDdYWcf5RJJTGfW35Tzqu8g0XA0VaiFLtySoXT+q7LpWyI6okU3T88JV8PDldZEZORICj7YrHzDwPb5yG8sCO7IJWZ8UlLhUww2BUIEFWpaB3q/FqIZuVeeIfwZ+JKko31FXQ9e9VtbxPwePeYc1wu8tYM5KUvLKEJ/UQNPJY63T+D2Tu84wNKTMAn/1JbIXlMolFhVvpNIU8AKMebt+R2UfPddu5hAbKdcB/lTSGKffRtO+WxwikPIrbKR0xBM25cWFt6yhLTHcVspomT9ZgR5tt/T1IW7fVGi/Vjqv8vmJc7pqakn1Pca1RuWXlDLt3ppyPdaI1+e3PKHL72h2wheJBEMs5vkFjFOphcspVbQ8+y41X0OIHyt2DCp6U5wImraKdtBd14o4rOkzfLmSC9bKY3oWZIIVI8AbU4H3RWzC84KGdgeY=
    - secure: hMgVnouIRo5w7tjtWTe9aJGWI68VjuFVKm+KqZKe2PwxR/JpYuvEPST24+nxdJMpgPr8E+9sz5hgr5EcQQ74n7eWZowHiGmXMrOIaiEJUiXHWMsEj8spfZ6eiGVBDtKma0YkLtZ2QNH5r8qaQDFmc0ZPI1Zmx0gVxQPr2bIBh6zAauiwPFucx0vW6+aT1PFkpSHIAnlCFE2gIm027OfRi6rCYBZLnwOlv92o+qKdPk0DFGtOgfkk00QIBYEpbaVJXR4nwoRDADb6nmrTtvJ03HzKczRDXgaj5Ze6PC+4KAHORJ5PZjrQ3CTxGhZCiqM/fRjyklBOh0d/hOErm7ZGoH656pPkKGZEQrYptT0l0+LDUK98TOD69gokbIFN+NFbGV540OiGuX4Kj6n/17kxeDdhe8/lA7xTpyylLvQyH7QtDcg1yzvMvB4ZkOQGHMMej7eH9lKewjdFQMX3vTE0V0tOx65JdXP3w5BEO07HEoXqCZdOebZUB5FI7o8y18dep4yvNap0qbsqOkf8IWGaAnxXWlV1rZFN0qW5TvaDYy5myyaX0+w6EibNed3Z9lA9xftVzI9NrYxxGduQki1NuU4Uj1GDQ6rTS8hn+O32sD9pqTyGVL6AZyAIwaImhe65xulwn18DQtU+sYARdMHBnFPEemPDw6kMlcAxYcXfXrw=

deploy:
  skip_cleanup: true
  provider: script
  script: utils/release.sh
  on:
    repo: strvcom/atlas.js
    branch: release
    node_js: '8'
